# AIM : To perform basic data analytics tasks in Python using NumPy and Pandas, including vector operations, mathematical operations, and DataFrame creation, reading, and handling.

**Procedure**

**Step 1 :** Import Required Libraries:
Begin by importing NumPy and Pandas using import numpy as np and import pandas as pd.

**Step 2:** Perform Vector and Mathematical Operations:
Create NumPy arrays and perform basic operations such as addition, subtraction, multiplication, division, mean, median, and standard deviation.

**Step 3 :** Create and Handle Pandas DataFrame:
Construct a DataFrame manually using pd.DataFrame() or read from a file using pd.read_csv().

**Step 4 :** Inspect and Analyze Data:
Use basic DataFrame functions like head(), info(), describe(), shape, and indexing to understand and manipulate the dataset.

`Before going to this let's understand the PYTHON CORE CONCEPTS`

#To understand how to declare variables and store different types of values in Python.

In [2]:
# Declaring different data types

name = "Amit"        # String
age = 22             # Integer
height = 5.9         # Float
is_student = True    # Boolean

print("Name:", name)
print("Age:", age)
print("Height:", height)
print("Is Student:", is_student)


Name: Amit
Age: 22
Height: 5.9
Is Student: True


#To perform arithmetic operations using values entered by the user.

In [3]:
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Addition =", num1 + num2)
print("Subtraction =", num1 - num2)
print("Multiplication =", num1 * num2)
print("Division =", num1 / num2)


Enter first number: 10
Enter second number: 20
Addition = 30
Subtraction = -10
Multiplication = 200
Division = 0.5


#To compare values using comparison and logical operators.

In [4]:
a = 10
b = 20

print(a == b)   # Equal
print(a != b)   # Not equal
print(a < b)    # Less than
print(a > b)    # Greater than

x = True
y = False
print(x and y)
print(x or y)
print(not x)


False
True
True
False
False
True
False


#To apply decision-making using if-else conditions.

In [5]:
age = int(input("Enter age: "))

if age >= 18:
    print("Eligible for Voting")
else:
    print("Not Eligible")


Enter age: 20
Eligible for Voting


#To understand repetitive execution using for and while loops.

In [6]:
marks = [78, 90, 85]

for m in marks:           # for loop
    print("Marks:", m)

count = 1                 # while loop
while count <= 5:
    print("Count:", count)
    count += 1


Marks: 78
Marks: 90
Marks: 85
Count: 1
Count: 2
Count: 3
Count: 4
Count: 5


#To generate a sequence of numbers using the range function.

In [7]:
for i in range(1, 6):       # 1 to 5
    print(i)

print(list(range(0, 10, 2)))  # Even numbers


1
2
3
4
5
[0, 2, 4, 6, 8]


#To control loop flow using break and continue statements.

In [8]:
for i in range(1, 10):
    if i == 6:
        break
    print(i)

for j in range(1, 10):
    if j == 6:
        continue
    print(j)


1
2
3
4
5
1
2
3
4
5
7
8
9


#To create and call user-defined functions in Python.

In [11]:
def greet(name):
    print("Hello", name, "Welcome!")

greet("XYZ")   # function call


Hello XYZ Welcome!


#To extract substrings and apply string built-in functions.

In [14]:
text = "PYThON PROGRAMMinG"

print(text[0:6])      # Slicing
print(text[::-1])     # Reverse
print(text.upper())   # Uppercase
print(text.lower())   # Lowercase
print(text.split())   # Split string


PYThON
GniMMARGORP NOhTYP
PYTHON PROGRAMMING
python programming
['PYThON', 'PROGRAMMinG']


#To implement list operations including slicing and built-in methods.

In [29]:
numbers = [10, 20, 30, 40, 50]

print(numbers[1:4])    # Slicing

[20, 30, 40]


In [30]:
numbers.append(60)
print(numbers)

[10, 20, 30, 40, 50, 60]


In [31]:
numbers.insert(5, 15)
print(numbers)

[10, 20, 30, 40, 50, 15, 60]


In [32]:
numbers.remove(20)
print(numbers)

[10, 30, 40, 50, 15, 60]


In [33]:
numbers.sort()
print(numbers)

[10, 15, 30, 40, 50, 60]


#To understand immutable ordered data stored using tuple.

A Tuple is a collection data type in Python used to store multiple values in a single variable.

**Syntax:**

variable_name = (value1, value2, value3)




Tuples are immutable, which means:

You cannot insert new values

You cannot delete specific elements

You cannot update existing values

So operations like append(), remove(), insert(), pop() do not exist for tuples.


In [41]:
# ---------------- Tuple Creation ----------------
t = (10, 20, 30, 40, 20)
print("Original Tuple:", t)

# ---------------- Accessing Elements -------------
print("\nAccessing Elements:")
print(t[0])      # First element
print(t[-1])     # Last element

# ---------------- Slicing ------------------------
print("\nSlicing:")
print(t[1:4])    # From index 1 to 3
print(t[:3])     # Beginning to index 2
print(t[2:])     # From index 2 to end

# ---------------- Searching (Find) ---------------
print("\nSearching / Finding:")
print("Count of 20:", t.count(20))
print("Index of 30:", t.index(30))

# ---------------- Looping ------------------------
print("\nLooping Elements:")
for i in t:
    print(i)

# ---------------- Concatenation ------------------
print("\nConcatenation:")
t1 = (50, 60)
new_tuple = t + t1
print("After Concatenation:", new_tuple)

# ---------------- Repetition ---------------------
print("\nRepetition:")
print(t1 * 3)    # Repeat tuple values

# ---------------- Membership ---------------------
print("\nMembership:")
print(20 in t)
print(100 not in t)
print(200 in t)

# ---------------- Length -------------------------
print("\nLength:")
print(len(t))

# ---------------- Built-in Functions -------------
print("\nBuilt-in Functions:")
print("Min:", min(t))
print("Max:", max(t))
print("Sum:", sum(t))



Original Tuple: (10, 20, 30, 40, 20)

Accessing Elements:
10
20

Slicing:
(20, 30, 40)
(10, 20, 30)
(30, 40, 20)

Searching / Finding:
Count of 20: 2
Index of 30: 2

Looping Elements:
10
20
30
40
20

Concatenation:
After Concatenation: (10, 20, 30, 40, 20, 50, 60)

Repetition:
(50, 60, 50, 60, 50, 60)

Membership:
True
True
False

Length:
5

Built-in Functions:
Min: 10
Max: 40
Sum: 120


In [42]:
# ---------------- Nested Tuple --------------------
nested = (1, 2, (3, 4, 5),(6,7),(8,9,10,11))
print("\nNested Tuple:", nested)
print("Access nested element:", nested[2][1])
print("Access nested element:", nested[3][1])
print("Access nested element:", nested[4][3])

# ---------------- Packing & Unpacking -------------
print("\nPacking / Unpacking:")
data = ("Raj", 21, "IT")
name, age, branch = data
print(name, age, branch)




Nested Tuple: (1, 2, (3, 4, 5), (6, 7), (8, 9, 10, 11))
Access nested element: 4
Access nested element: 7
Access nested element: 11

Packing / Unpacking:
Raj 21 IT


In [44]:
# -------- Insert, Delete using Conversion
print("Insert / Delete Using List Conversion (because tuple immutable):")

temp = list(t)        # Convert tuple to list
temp.insert(2, 25)    # Insert 25 at index 2
t = tuple(temp)
print("After Insert:", t)

temp = list(t)        # Convert again
temp.remove(20)       # Remove first occurrence of 20
t = tuple(temp)
print("After Delete:", t)

# -------- Display Error Demonstration (immutability) --------
print("\nError Demonstration:")
try:
    original = (1, 2, 3)
    original[0] = 100  # Not allowed
except TypeError:
    print("Error: Tuple does not support item assignment (immutable)")

Insert / Delete Using List Conversion (because tuple immutable):
After Insert: (10, 25, 25, 30, 40, 20)
After Delete: (10, 25, 25, 30, 40)

Error Demonstration:
Error: Tuple does not support item assignment (immutable)


In [45]:
original = (1, 2, 3)
original[0] = 100  # Not allowed

TypeError: 'tuple' object does not support item assignment

#To perform operations on sets such as union and intersection.

In [46]:
A = {1, 2, 3, 4}
B = {3, 4, 5, 6}

print(A.union(B))
print(A.intersection(B))


{1, 2, 3, 4, 5, 6}
{3, 4}


#To store data in key-value format and perform CRUD operations.

In [50]:
student = {"name": "Rahul", "age": 20, "marks": 85}

print(student["name"])           # Read
student["marks"] = 90            # Update
student["city"] = "Surat"        # Create
del student["age"]               # Delete

print(student)


Rahul
{'name': 'Rahul', 'marks': 90, 'city': 'Surat'}


A Dictionary is a collection of key-value pairs in Python.

Data is stored in the form: Key : Value

Keys must be unique, values can be duplicate.

It is mutable (we can change values).

It is unordered (Python 3.6+ maintains insertion order, but still we call unordered).

Created using curly braces {}

In [54]:
# AIM: To perform all dictionary operations in Python

# ---------------- Dictionary Creation ----------------
student = {
    "name": "XYZ",
    "age": 24,
    "branch": "IT",
    "cgpa": 8.5
}
print("Original Dictionary:", student)

# ---------------- Accessing Elements ------------------
print("\nAccessing Values:")
print(student["name"])          # Access by key
print(student.get("cgpa"))      # Using get()

# ---------------- Updating Values ---------------------
print("\nUpdating Value:")
student["age"] = 25             # Update age
print("After Update:", student)

# ---------------- Insert New Key-Value ----------------
print("\nInsert New Value:")
student["city"] = "Ahmedabad"   # Insert new data
print("After Insert:", student)

# ---------------- Delete Operations -------------------
print("\nDelete Operations:")
student.pop("branch")           # Remove given key
print("After pop():", student)

student.popitem()               # Removes last inserted item
print("After popitem():", student)

del student["age"]              # Delete specific key
print("After del operation:", student)

# ---------------- Dictionary Functions ----------------
print("\nDictionary Functions:")
print("Keys:", student.keys())
print("Values:", student.values())
print("Items:", student.items())

# ---------------- Looping in Dictionary ---------------
print("\nLooping Through Dictionary:")
for key in student:
    print(key, ":", student[key])

# ---------------- Membership --------------------------
print("\nMembership Test:")
print("name" in student)        # True
print("cgpa" not in student)    # True

# ---------------- Length of Dictionary ----------------
print("\nLength:", len(student))

# ---------------- Clearing Dictionary -----------------
copy_dict = student.copy()
student.clear()
print("\nAfter Clear:", student)
print("Copied Dictionary:", copy_dict)

# ---------------- Nested Dictionary -------------------
print("\nNested Dictionary:")
college = {
    "department": {
        "hod": "abc",
        "students": 120,
        "labs": 5
    }
}
print(college)
print("Access nested:", college["department"]["hod"])

# ---------------- Converting List to Dictionary -------
#The zip() function is used to combine two or more
#iterables (like lists, tuples, etc.) element-wise into pairs.
print("\nList to Dictionary Conversion:")
keys = ["a", "b", "c"]
values = [1, 2, 3]
result = dict(zip(keys, values))
print(result)

# ---------------- Dictionary from List of Tuples -------
tuple_list = [("x", 10), ("y", 20)]
print("\nDictionary from tuple list:", dict(tuple_list))


Original Dictionary: {'name': 'XYZ', 'age': 24, 'branch': 'IT', 'cgpa': 8.5}

Accessing Values:
XYZ
8.5

Updating Value:
After Update: {'name': 'XYZ', 'age': 25, 'branch': 'IT', 'cgpa': 8.5}

Insert New Value:
After Insert: {'name': 'XYZ', 'age': 25, 'branch': 'IT', 'cgpa': 8.5, 'city': 'Ahmedabad'}

Delete Operations:
After pop(): {'name': 'XYZ', 'age': 25, 'cgpa': 8.5, 'city': 'Ahmedabad'}
After popitem(): {'name': 'XYZ', 'age': 25, 'cgpa': 8.5}
After del operation: {'name': 'XYZ', 'cgpa': 8.5}

Dictionary Functions:
Keys: dict_keys(['name', 'cgpa'])
Values: dict_values(['XYZ', 8.5])
Items: dict_items([('name', 'XYZ'), ('cgpa', 8.5)])

Looping Through Dictionary:
name : XYZ
cgpa : 8.5

Membership Test:
True
False

Length: 2

After Clear: {}
Copied Dictionary: {'name': 'XYZ', 'cgpa': 8.5}

Nested Dictionary:
{'department': {'hod': 'abc', 'students': 120, 'labs': 5}}
Access nested: abc

List to Dictionary Conversion:
{'a': 1, 'b': 2, 'c': 3}

Dictionary from tuple list: {'x': 10, 'y': 

In [55]:
#To iterate through dictionary keys and values using loops.
student = {"name": "Rahul", "course": "IT", "marks": 92}

for key, value in student.items():
    print(key, ":", value)


name : Rahul
course : IT
marks : 92


In [57]:
#To handle runtime errors gracefully using try-except.
try:
    num = int(input("Enter number: "))
    print("Square =", num ** 2)
except:
    print("Invalid Input!")


Enter number: 5.2
Invalid Input!


In [58]:
#To use built-in Python modules such as math and random.
import math
import random

print(math.sqrt(25))
print(random.randint(1, 10))


5.0
8


#What is NumPy?

NumPy stands for Numerical Python.

It is a library in Python used for efficient numerical computations.

It provides a high-performance multidimensional array object called ndarray.

Supports mathematical, logical, statistical, and linear algebra operations on arrays.

Much faster and more memory-efficient than Python lists.

In [65]:
# AIM: To demonstrate all core concepts of NumPy

import numpy as np

# ---------------- Array Creation ----------------
print(" 1️ Array Creation")
arr1 = np.array([1, 2, 3, 4, 5])              # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])       # 2D array
zeros = np.zeros((2,3))                        # Array of zeros
ones = np.ones((2,3))                          # Array of ones
arange_arr = np.arange(0, 10, 2)   # Values from 0 to 10 with step 2
linspace_arr = np.linspace(0, 1, 5) # 5 evenly spaced numbers between 0 and 1

print("1D array:", arr1)
print("2D array:\n", arr2)
print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# ---------------- Array Attributes ----------------
print("\n 2️ Array Attributes")
print("Shape of arr2:", arr2.shape)
print("Number of dimensions:", arr2.ndim)
print("Data type:", arr1.dtype)
print("Size:", arr1.size)

# ---------------- Indexing & Slicing ----------------
print("\n 3 Indexing & Slicing")
print("Element arr2[1,2]:", arr2[1,2])         # Access specific element
print("Slice arr1[1:4]:", arr1[1:4])           # Slice elements
print("2D slice arr2[:,1]:", arr2[:,1])        # Second column

# ---------------- Arithmetic Operations ----------------
print("\n 4️ Arithmetic Operations")
a = np.array([10,20,30])
b = np.array([1,2,3])
print("Add:", a + b)
print("Subtract:", a - b)
print("Multiply:", a * b)
print("Divide:", a / b)
print("Square:", a ** 2)

# ---------------- Statistical Operations ----------------
print("\n 5️ Statistical Operations")
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Median:", np.median(arr1))
print("Standard Deviation:", arr1.std())
print("Max:", arr1.max())
print("Min:", arr1.min())

# ---------------- Vectorized Operations ----------------
print("\n 6️ Vectorized Operations")
print("Add 5 to all elements:", arr1 + 5)
print("Multiply by 2:", arr1 * 2)

# ---------------- Reshape & Transpose ----------------
print("\n 7️ Reshape & Transpose")
arr3 = np.arange(1,13)
arr3_reshaped = arr3.reshape(3,4)
print("Reshaped array (3x4):\n", arr3_reshaped)
print("Transpose:\n", arr3_reshaped.T)

# ---------------- Stacking & Splitting ----------------
print("\n 8️ Stacking & Splitting")
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])
stacked = np.vstack((arr_a, arr_b))
stacked1 = np.hstack((arr_a, arr_b))
print("Vertical Stack:\n", stacked)
print("Horizontal Stack:\n", stacked1)
split_arr = np.array_split(arr3, 3)
print("Split array into 3 parts:", split_arr)

# ---------------- Copy vs View ----------------
print("\n 9️ Copy vs View")
original = np.array([1,2,3])
view_arr = original.view()
copy_arr = original.copy()
view_arr[0] = 100
copy_arr[1] = 200
print("Original after view change:", original) # View affects original
print("Copy array:", copy_arr)             # Copy does not affect original

# ---------------- Mathematical Functions ----------------
print("\n 10 Mathematical Functions")
print("Square Root:", np.sqrt(arr1))
print("Exponential:", np.exp([1,2]))
print("Logarithm:", np.log([1, np.e, np.e**2]))
print("Sin:", np.sin([0, np.pi/2, np.pi]))

# ---------------- Linear Algebra ----------------
print("\n 11 Linear Algebra")
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Matrix Dot Product:\n", np.dot(matrix1, matrix2))
print("Matrix Determinant:", np.linalg.det(matrix1))
print("Matrix Inverse:\n", np.linalg.inv(matrix1))


 1️ Array Creation
1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]

 2️ Array Attributes
Shape of arr2: (2, 3)
Number of dimensions: 2
Data type: int64
Size: 5

 3 Indexing & Slicing
Element arr2[1,2]: 6
Slice arr1[1:4]: [2 3 4]
2D slice arr2[:,1]: [2 5]

 4️ Arithmetic Operations
Add: [11 22 33]
Subtract: [ 9 18 27]
Multiply: [10 40 90]
Divide: [10. 10. 10.]
Square: [100 400 900]

 5️ Statistical Operations
Sum: 15
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Max: 5
Min: 1

 6️ Vectorized Operations
Add 5 to all elements: [ 6  7  8  9 10]
Multiply by 2: [ 2  4  6  8 10]

 7️ Reshape & Transpose
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transpose:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]

 8️ Stacking & Splitting
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Split array into 3 parts: [arr

#What is Pandas?

Pandas is a Python library for data manipulation and analysis.

The name comes from “Panel Data” (multi-dimensional data).

Built on top of NumPy, so it is fast and efficient for numerical operations.

Provides easy-to-use data structures and data analysis tools.

In [84]:
# AIM: To demonstrate all core Pandas concepts in a single practical

import pandas as pd
import numpy as np

# ---------------- Series Creation ----------------
print("1️ Series Creation")
data = [10, 20, 30, 40]
series1 = pd.Series(data)                  # From list
series2 = pd.Series(data, index=['a','b','c','d'])  # Custom index
series3 = pd.Series({'x':1, 'y':2, 'z':3})         # From dictionary
print("Series from list:\n", series1)
print("Series with custom index:\n", series2)
print("Series from dictionary:\n", series3)

# ---------------- DataFrame Creation ----------------
print("\n2️ DataFrame Creation")
data_dict = {
    'Name': ['Raj', 'Priya', 'Anil'],
    'Age': [22, 21, 23],
    'Course': ['CSE', 'IT', 'EC'],
    'CGPA': [8.5, 9.0, 7.8]
}
df = pd.DataFrame(data_dict)
print("DataFrame:\n", df)

# ---------------- Indexing & Selecting ----------------
print("\n3️ Indexing & Selecting")
print("Select 'Name' column:\n", df['Name'])
print("Select multiple columns:\n", df[['Name','CGPA']])
print("Select row by index (iloc):\n", df.iloc[1])
print("Select row by label (loc):\n", df.loc[0])

# ---------------- Adding & Updating Columns ----------------
print("\n4️ Adding / Updating Columns")
df['Grade'] = ['A', 'A+', 'B']   # Add new column
df['CGPA'] = df['CGPA'] + 0.1    # Update existing column
print(df)

# ---------------- Deleting Columns / Rows ----------------
print("\n5️ Deleting Columns / Rows")
df_drop_col = df.drop('Grade', axis=1)  # Drop column (returns new DF)
df_drop_row = df.drop(1, axis=0)        # Drop row at index 1
print("After dropping column:\n", df_drop_col)
print("After dropping row:\n", df_drop_row)

# ---------------- Filtering / Conditional Selection ----------------
print("\n6️ Filtering / Conditional Selection")
print(df[df['CGPA'] > 8.5])           # Students with CGPA > 8.5
print(df[(df['CGPA'] > 8.0) & (df['Age'] < 23)])  # Multiple conditions

# ---------------- Aggregation / Statistics ----------------
print("\n7️ Aggregation / Statistics")
print("Mean CGPA:", df['CGPA'].mean())
print("Max Age:", df['Age'].max())
print("Min CGPA:", df['CGPA'].min())
print("Describe DataFrame:\n", df.describe())

# ---------------- Sorting ----------------
print("\n8️ Sorting")
print("Sort by CGPA ascending:\n", df.sort_values('CGPA'))
print("Sort by Age descending:\n", df.sort_values('Age', ascending=False))

# ---------------- Handling Missing Data ----------------
print("\n9️ Handling Missing Data")
df_nan = df.copy()
df_nan.loc[2,'CGPA'] = np.nan
print("DataFrame with NaN:\n", df_nan)
print("Fill NaN with 0:\n", df_nan.fillna(2))
print("Drop rows with NaN:\n", df_nan.dropna())

# ---------------- Reading / Writing CSV ----------------
print("\n10 Reading / Writing CSV (Simulation)")
df.to_csv('students.csv', index=False)   # Write CSV
df_csv = pd.read_csv('students.csv')     # Read CSV
print("Read CSV DataFrame:\n", df_csv)



# ---------------- Indexing with set_index ----------------
print("\n11 Set Index")
df_indexed = df.set_index('Name')
print(df_indexed)

# ---------------- Selecting Rows with loc / iloc ----------------
print("\n1️2️ loc / iloc Selection")
print("Row of 'Raj':\n", df_indexed.loc['Raj'])
print("Second row (iloc):\n", df_indexed.iloc[1])
print(df_indexed.iloc[2,3])
print(df_indexed.loc['Priya','Course'])


1️ Series Creation
Series from list:
 0    10
1    20
2    30
3    40
dtype: int64
Series with custom index:
 a    10
b    20
c    30
d    40
dtype: int64
Series from dictionary:
 x    1
y    2
z    3
dtype: int64

2️ DataFrame Creation
DataFrame:
     Name  Age Course  CGPA
0    Raj   22    CSE   8.5
1  Priya   21     IT   9.0
2   Anil   23     EC   7.8

3️ Indexing & Selecting
Select 'Name' column:
 0      Raj
1    Priya
2     Anil
Name: Name, dtype: object
Select multiple columns:
     Name  CGPA
0    Raj   8.5
1  Priya   9.0
2   Anil   7.8
Select row by index (iloc):
 Name      Priya
Age          21
Course       IT
CGPA        9.0
Name: 1, dtype: object
Select row by label (loc):
 Name      Raj
Age        22
Course    CSE
CGPA      8.5
Name: 0, dtype: object

4️ Adding / Updating Columns
    Name  Age Course  CGPA Grade
0    Raj   22    CSE   8.6     A
1  Priya   21     IT   9.1    A+
2   Anil   23     EC   7.9     B

5️ Deleting Columns / Rows
After dropping column:
     Name  Age

In [70]:
!ls

sample_data  students.csv


In [73]:
import pandas as pd

url = "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv"
df = pd.read_csv(url)

print(df.head())       # First 5 rows
print(df.info())       # Dataframe info: columns, types, non‑null counts


# Save CSV
df.to_csv("iris.csv", index=False)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


#What is index in a DataFrame?

Every Pandas DataFrame has an index — it’s like the row labels.

By default, when you create a DataFrame, Pandas assigns 0, 1, 2, … as row indices.
eg . index = True
,Name,Age
0,Raj,22
1,Priya,21

index=False
Name,Age
Raj,22
Priya,21